version: "3"

services:
  web:
    container_name: dsp-anal-app
    build:
      context: .
      network: host
    ports:
      - "5000:5000"
    volumes:
      - /mnt/d/workspace/dev/dsp-analysis-app:/app
