version: '3'

services:
    dict_db_postgres:
        image: postgres:14.0-alpine
        container_name: DS_dict_db
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "${DB_USER_ID}"
            POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
        volumes:
            - ${WORKSPACE_DIR}/db:/var/lib/postgresql/data
    web_app_dict:
        build: ./DSweb
        container_name: DS_dict_web
        ports:
            - "3838:3838"
        environment:
            GRANT_SUDO: 'yes'
        volumes:
            - ${WORKSPACE_DIR}/shiny:/srv/shiny-server/
            - ${WORKSPACE_DIR}/shiny/log:/var/log/shiny-server/